<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="tarunsahu" failures="0" tests="5" name="Test" time="182.614" errors="0" timestamp="2024-09-21T22:40:25 IST">
  <testcase classname="Test_base.Test_base" name="@BeforeTest start" time="180.487">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &amp;apos;TARUNSAHU&amp;apos;, ip: &amp;apos;192.168.58.132&amp;apos;">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'TARUNSAHU', ip: '192.168.58.132'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
at Test_base.Test_base.start(Test_base.java:72)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:396)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:352)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
... 28 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:379)
... 38 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest start -->
  <testcase classname="Test_base.Test_base" name="@AfterClass teaedown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass teaedown -->
  <testcase classname="Test_Cases.TC004" name="verify_loginDDT" time="0.0">
    <skipped/>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="Test_Cases.TC004" name="verify_loginDDT" time="0.0">
    <skipped/>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="Test_Cases.TC004" name="verify_loginDDT" time="0.002">
    <skipped/>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="Test_Cases.TC004" name="verify_loginDDT" time="0.0">
    <skipped/>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="Test_Cases.TC004" name="verify_loginDDT" time="0.0">
    <skipped/>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
